language: python
python:
 - "3.9"
# - "3.10"
# - "3.11"
# - "3.12"
before_install:
 - pip install 'urllib3<2.0' #Enforce SSL version to be able to run twine
 - pip install -U pytest
 - pip install -U build
 - pip install --upgrade twine
# - pip install codecov
install:
 - pip install -r requirements.txt
 - pip install .
env:
 global:
  - PYTHONPATH=src:test
script:
# - pytest
 - python -m build
after_success:
 - python -m twine upload --skip-existing --verbose --repository testpypi dist/*
# - codecov
#deploy:
#  provider: pypi
#  server: https://test.pypi.org
#  edge: true # opt in to dpl v2
#  skip_existing: true
#  script: build.sh
#  distributions: "sdist bdist_wheel"
#  on:
#   all_branches: true # For testing only. Comment once the script is running
 # tags: true # Uncomment this line to publish when the tag is created