language: python
python:
 - "3.9"
before_install:
 - pip install 'urllib3<2.0' #Enforce SSL version to be able to run twine
 - pip install -U pytest
 - pip install -U build
 - pip install -U twine
 - pip install codecov
install:
 - pip install -r requirements.txt
 - pip install .
env:
 global:
  - PYTHONPATH=src:test
script:
 - pytest
 - python -m build
after_success:
 - codecov
deploy:
  provider: script
  script: python -m twine upload --skip-existing --verbose --repository testpypi dist/*
  on:
   all_branches: true # uncomment for testing purposes
   #branch: prod # uncomment on production
   #tags: true # uncomment on production
