language: python
python:
 - "3.9"
before_install:
 - pip install -U pytest
 - pip install codecov
install:
 - pip install -r requirements.txt
 - pip install .
env:
 global:
  - PYTHONPATH=src:test
#script:
# - pytest
#after_success:
# - codecov
deploy:
  provider: pypi
  server: https://test.pypi.org
  edge: true # opt in to dpl v2
  skip_existing: True
