language: python
python:
 - "3.9"
# - "3.10"
# - "3.11"
# - "3.12"
# - "3.13"
before_install:
 - pip install -U pytest
# - pip install codecov
install:
 - pip install -r requirements.txt
# - pip install .
env:
 global:
  - PYTHONPATH=src:test
script:
# - pytest
 - python -V
#after_success:
# - codecov
deploy:
  provider: pypi
  server: https://test.pypi.org
  edge: true # opt in to dpl v2
  skip_existing: true
  distributions: "bdist_hatchling"
  script: python -m build
  on:
   all_branches: true # For testing only. Comment once the script is running
 # tags: true # Uncomment this line to publish when the tag is created