#
# Copyright IBM Corp. 2024 - 2026
# SPDX-License-Identifier: Apache-2.0
#

import logging
import os
from html import escape
from typing import Optional

from javacore_analyser.plugin_manager import PluginManager


class PluginCoordinator:
    """Coordinates plugin discovery, execution, and XSL/HTML generation."""

    @staticmethod
    def process_plugins(javacore_analyzer):
        """Discover and run all enabled plugins, storing results in javacore_analyzer.plugin_data.

        All errors are handled gracefully with logging so plugin failures do not
        break the main analysis workflow.

        Args:
            javacore_analyzer: A JavacoreAnalyzer (or JavacoreSet) instance whose ``path``
                and ``plugin_data`` attributes will be used/populated.
        """
        try:
            logging.info("Plugin processing enabled, initializing plugin manager")
            javacore_analyzer.plugin_manager = PluginManager()

            # Discover and load plugins
            javacore_analyzer.plugin_manager.discover_plugins()
            plugins = javacore_analyzer.plugin_manager.get_all_plugins()

            if not plugins:
                logging.info("No plugins found in plugin directory")
                return

            logging.info(f"Found {len(plugins)} plugin(s), scanning for matching files")

            # Find files for each plugin
            plugin_files = javacore_analyzer.plugin_manager.find_files_for_plugins(javacore_analyzer.path)

            if not plugin_files:
                logging.info("No files found matching any plugin patterns")
                return

            # Process files with each plugin
            for plugin, files in plugin_files.items():
                try:
                    logging.info(f"Processing {len(files)} file(s) with plugin: {plugin.get_display_name()}")
                    data = plugin.process_files(files)
                    javacore_analyzer.plugin_data[plugin.get_plugin_name()] = {
                        'plugin': plugin,
                        'data': data,
                        'files': files
                    }
                    logging.info(f"Successfully processed files with plugin: {plugin.get_display_name()}")
                except Exception as e:
                    logging.error(f"Error processing files with plugin {plugin.get_display_name()}: {e}")

        except Exception as e:
            logging.error(f"Error during plugin processing: {e}")

    @staticmethod
    def generate_plugin_section_header(section_id: str, section_title: str, description: str) -> str:
        """Generate a standardised HTML header for plugin sections.

        The generated HTML includes:
        - A collapsible section header (h3) with expand/collapse functionality
        - A nested documentation section explaining what the section contains
        - Proper CSS classes for styling consistency

        Args:
            section_id: Unique identifier for the section (used in HTML IDs and JavaScript)
            section_title: Human-readable title displayed in the section header
            description: HTML content describing what the section shows

        Returns:
            str: HTML string containing the section header and documentation wrapper
        """
        escaped_title = escape(section_title)
        header_html = (
            f'<h3><a id="toggle_{section_id}" '
            f'href="javascript:expand_it({section_id},toggle_{section_id})" '
            f'class="expandit">{escaped_title}</a></h3>\n'
            f'<div id="{section_id}" style="display:none;">\n'
            f'    <a id="toggle{section_id}doc" '
            f'href="javascript:expand_it({section_id}doc,toggle{section_id}doc)" '
            f'class="expandit">\n'
            f'        What does this section tell me?</a>\n'
            f'    <div id="{section_id}doc" style="display:none;">\n'
            f'        {description}\n'
            f'    </div>\n\n'
        )
        return header_html

    @staticmethod
    def generate_plugins_xsl(temp_dir: str, plugin_data: dict) -> Optional[str]:
        """Generate plugins.xsl file dynamically from loaded plugin HTML content.

        Creates a plugins.xsl file that wraps HTML content generated by plugins into a
        single XSL template named "plugins". The generated file is used by report.xsl to
        include plugin-specific content in the final HTML report.

        Args:
            temp_dir (str): Temporary directory where XSL files are stored.
            plugin_data (dict): Dictionary of loaded plugin data, where keys are plugin
                names and values are dictionaries containing 'plugin' instances and 'data'.

        Returns:
            Optional[str]: Path to the generated plugins.xsl file, or None if generation fails.
        """
        plugins_xsl_path = os.path.join(temp_dir, "plugins.xsl")

        try:
            plugins_xsl_content = '''<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template name="plugins">
'''
            if plugin_data:
                logging.info("Generating plugins.xsl with plugin HTML content")

                for plugin_name, plugin_info in plugin_data.items():
                    try:
                        plugin = plugin_info['plugin']
                        data = plugin_info.get('data', {})

                        html_content = plugin.generate_html(data)

                        if html_content:
                            section_id = plugin_name.replace('_', '')
                            section_header = PluginCoordinator.generate_plugin_section_header(
                                section_id=section_id,
                                section_title=plugin.get_display_name(),
                                description=plugin.get_description()
                            )
                            full_html = section_header + html_content + '\n</div>\n'
                            plugins_xsl_content += (
                                f'\n        <!-- Plugin: {plugin.get_display_name()} -->\n'
                                f'        <xsl:text disable-output-escaping="yes"><![CDATA[\n'
                                f'{full_html}\n'
                                f'        ]]></xsl:text>\n\n'
                            )
                            logging.info(f"Added HTML content for plugin: {plugin.get_display_name()}")
                        else:
                            logging.debug(f"Plugin {plugin.get_display_name()} returned no HTML content")

                    except Exception as e:
                        logging.error(f"Error generating HTML for plugin {plugin_name}: {e}")
                        logging.exception(e)
                        safe_error = str(e).replace('<', '&lt;').replace('>', '&gt;')
                        plugins_xsl_content += (
                            f'\n        <!-- Plugin: {plugin_name} - Error generating HTML -->\n'
                            f'        <xsl:text disable-output-escaping="yes"><![CDATA[\n'
                            f'        <div class="error_row" style="padding: 10px; margin: 10px 0;">\n'
                            f'            <strong>Error in plugin {plugin_name}:</strong> {safe_error}\n'
                            f'        </div>\n'
                            f'        ]]></xsl:text>\n\n'
                        )
            else:
                plugins_xsl_content += "        <!-- No plugins loaded -->\n"

            plugins_xsl_content += '    </xsl:template>\n\n</xsl:stylesheet>\n\n<!-- Made with Bob -->\n'

            with open(plugins_xsl_path, 'w', encoding='utf-8') as f:
                f.write(plugins_xsl_content)

            logging.info(f"Generated plugins.xsl at {plugins_xsl_path}")
            return plugins_xsl_path

        except Exception as e:
            logging.error(f"Error generating plugins.xsl: {e}")
            # Create empty plugins.xsl to prevent XSL errors
            try:
                with open(plugins_xsl_path, 'w', encoding='utf-8') as f:
                    f.write(
                        '<?xml version="1.0" encoding="UTF-8"?>\n'
                        '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">\n'
                        '    <xsl:template name="plugins">\n'
                        '        <!-- Error generating plugin templates -->\n'
                        '    </xsl:template>\n'
                        '</xsl:stylesheet>\n'
                    )
                return plugins_xsl_path
            except Exception:
                return None
